from flask import Flask
from degas.model.predict import load_model, predict

app = Flask(__name__)


def init():
    global model
    # load the pre-trained Keras model
    model = load_model()


@app.route('/v1')
def hello():
    return 'Hello, World!'


# no reason to get all dynamic here; we only host one model right now.
@app.route("/v1/models/degas/1")
def model_status():
    return {}


@app.route("/v1/models")
def models_status():
    return {"name": "degas",
            "version": 1}


@app.route("/v1/models/degas")
def predict(domains):
    """
    Predict whether one or more domains were generated by a DGA.

    Return format is designed to be close to Tensorflow Serving, to allow users to transition from this API to Serving
    with minimal rework.
    [
        [{"label": "dga",
         "score": 0.82},
         {"label": "benign",
          "score": 0.18}],
    ]
    """
