name: degas
dependencies: 
  # Tensorflow doesn't support 3.7 yet :(
 - python=3.6.7
 - numpy
 - pandas
 - scikit-learn>=0.20.2
 #- jupyter 
 #- jupyterlab
 - scipy 
 - seaborn
 - matplotlib
 - Click
 - python-dotenv=0.20.0
 - typing
 - tensorflow=1.11.0
 - h5py=2.10.0

